apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    name: db-service
    app: demo-voting-app
  ports:
  - port: 5432  
    targetPort: 5432
  selector:
    name: postgres-pod
    app: demo-voting-app

