apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    name: redis-service
    app: demo-voting-app
  ports:
  - port: 6379
    targetPort: 6379
  selector:
    name: redis-pod
    app: demo-voting-app

