apiVersion: v1
kind: Service
metadata:
  name: voting-service
spec:
  type: LoadBalancer
  selector:
    name: voting-service
    app: demo-voting-app
  ports:
  - port: 80
    targetPort: 80
  selector:
    name: voting-app-pod
    app: demo-voting-app

